version: "3.9"

services:
  face_app:
    container_name: face_recognition_app
    build:
      context: .
      dockerfile: dockerfile 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn Project101.asgi:application
      --host 0.0.0.0
      --port 8000
      --reload
    environment:
      - PYTHONUNBUFFERED=1
