# Generated by Django 5.0.7 on 2025-03-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_course_session_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='employe',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='student',
            new_name='employe',
        ),
        migrations.RenameField(
            model_name='latecheckinpolicy',
            old_name='student',
            new_name='employe',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='student',
            new_name='employe',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='student',
            new_name='employe',
        ),
        migrations.AlterField(
            model_name='employe',
            name='department',
            field=models.ManyToManyField(related_name='employes', to='app1.department'),
        ),
    ]
