# Generated by Django 5.0.7 on 2025-03-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_student_attendance_employe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='fee',
        ),
        migrations.DeleteModel(
            name='AdvancePayment',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
    ]
