# Generated by Django 5.1.7 on 2025-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_roll_no_employe_emp_id_employe_allowances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='total_salary',
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Performance or festival bonus', max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Other deductions', max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime hours worked', max_digits=5),
        ),
        migrations.AddField(
            model_name='salary',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime rate per hour', max_digits=7),
        ),
        migrations.AddField(
            model_name='salary',
            name='tax_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Income tax deductions', max_digits=10),
        ),
    ]
