# Generated by Django 5.1.7 on 2025-04-11 10:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_salary_deductions_remove_salary_total_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='allowances',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Overtime rate per hour', max_digits=7),
        ),
    ]
