# Generated by Django 5.1.7 on 2025-03-11 11:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_salary_allowances_alter_salary_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
