# Generated by Django 5.1.7 on 2025-03-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_salary_absence_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
