# Generated by Django 5.1.7 on 2025-03-16 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_attendance_overtime_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='face_embedding',
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='app1.employe')),
            ],
        ),
    ]
