# Generated by Django 5.1.7 on 2025-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_employe_face_embedding_faceembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
