# Generated by Django 5.0.7 on 2025-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_employe_face_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='email_sent',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Partial', 'Partial')], default='Absent', max_length=20),
        ),
    ]
