# Generated by Django 5.0.7 on 2025-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_attendance_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Absent', max_length=20),
        ),
    ]
