# Generated by Django 5.0.7 on 2025-05-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_attendance_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
